# -*- coding: utf-8 -*-
"""qwen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDqEciy69DhgU3lohrWD7ymrHwv_Jhyb
"""

import os
import time
import gradio as gr
import pandas as pd

from transformers import pipeline

# Only public models (NO TOKEN REQUIRED)
MODEL_DEFINITIONS = {
    "Qwen 0.5B": "Qwen/Qwen2-0.5B-Instruct",
    "DistilGPT2": "distilgpt2"
}

# Load SQuAD dataset (light fallback)
def load_data():
    try:
        from datasets import load_dataset
        dataset = load_dataset("squad", split="train[:50]")
        return dataset.to_pandas()
    except:
        return pd.DataFrame({
            "context": ["AI is artificial intelligence."],
            "question": ["What is AI?"],
            "text": ["Artificial intelligence"]
        })

df = load_data()

# Cache model
def load_model(model_name):
    return pipeline("text-generation", model=model_name)

# Prompt generator
def build_prompt(context, question):
    return f"""Answer the question based on the passage.

Passage: {context}

Question: {question}

Answer:"""

# Generate answer
def generate(model_name, context, question, max_tokens, temp):
    pipe = load_model(model_name)
    prompt = build_prompt(context, question)

    start = time.time()
    output = pipe(prompt, max_new_tokens=max_tokens, temperature=temp)
    end = time.time()

    text = output[0]["generated_text"]

    return text, f"{end-start:.2f} sec"


# UI
with gr.Blocks() as app:
    gr.Markdown("# 🤖 AI Question Answering App (Gradio)")

    with gr.Row():
        model = gr.Dropdown(list(MODEL_DEFINITIONS.values()), label="Select Model", value="distilgpt2")
        max_tokens = gr.Slider(16, 200, value=64, label="Max Tokens")
        temp = gr.Slider(0.1, 1.0, value=0.7, label="Temperature")

    with gr.Row():
        context = gr.Textbox(value=df.loc[0, "context"], lines=6, label="Context")
        question = gr.Textbox(value=df.loc[0, "question"], label="Question")

    btn = gr.Button("Generate Answer")

    output = gr.Textbox(label="Generated Answer", lines=8)
    time_taken = gr.Textbox(label="Time Taken")

    btn.click(
        generate,
        inputs=[model, context, question, max_tokens, temp],
        outputs=[output, time_taken]
    )

    gr.Markdown("### 📊 Sample Data Preview")
    gr.Dataframe(df.head())

app.launch()