# -*- coding: utf-8 -*-
"""tinyllama_finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15kMxnLK8qDH-LyHcsFhlWXWdiR8-EkV6

# TinyLlama Fine-Tuning

# 1. Install Libraries
"""

!pip install -q transformers datasets peft accelerate bitsandbytes

"""# 2. Load the Base Model (TinyLlama)"""

import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from peft import LoraConfig, get_peft_model

print('Torch:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())

"""# 3. Prepare Your Dataset"""

dataset = load_dataset("squad")
train_small = dataset["train"].select(range(50))
val_small = dataset["validation"].select(range(10))

train_small, val_small

"""# 4. Convert Each Row into a Prompt"""

def format_item(example):
    answer = example["answers"]["text"][0] if example["answers"]["text"] else ""
    text = f"Context: {example['context']}\nQuestion: {example['question']}\nAnswer: {answer}"
    return {"text": text}

train_fmt = train_small.map(format_item)
val_fmt = val_small.map(format_item)

train_fmt[0]

"""# load the model"""

model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_id)
if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({"pad_token": "[PAD]"})

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    load_in_4bit=True
)

model.resize_token_embeddings(len(tokenizer))

print("Loaded TinyLlama in 4-bit!")

"""# 5. Tokenize the Dataset"""

def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

train_tok = train_fmt.map(tokenize, batched=True)
val_tok = val_fmt.map(tokenize, batched=True)

train_tok = train_tok.map(lambda x: {"labels": x["input_ids"]}, batched=True)
val_tok = val_tok.map(lambda x: {"labels": x["input_ids"]}, batched=True)

"""# 6. Apply LoRA (4GB-friendly training)"""

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

lora_cfg = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj","v_proj","k_proj","o_proj"],
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_cfg)
model.print_trainable_parameters()

"""# 7. Training Arguments"""

training_args = TrainingArguments(
    output_dir="tinyllama_squad_lora",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_train_epochs=1,
    logging_steps=5,
    save_steps=50,
    bf16=False,
    fp16=False,
    save_total_limit=2,
)

"""# 8. Start Training"""

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    tokenizer=tokenizer,
    data_collator=data_collator
)

trainer

"""# 9. Save the Trained Model"""

import wandb
wandb.init(project="tinyllama_squad_lora_finetune")
trainer.train()
trainer.save_model("tinyllama_squad_lora")
tokenizer.save_pretrained("tinyllama_squad_lora")

"""# 10. Inference Code"""

def ask(question, context):
    prompt = f"Context: {context}\nQuestion: {question}\nAnswer:"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    output = model.generate(**inputs, max_new_tokens=60)
    return tokenizer.decode(output[0], skip_special_tokens=True)

sample = val_small[0]
ask(sample["question"], sample["context"])

def ask(question, context="", max_new_tokens=80):
    prompt = f"Context: {context}\nQuestion: {question}\nAnswer:"

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    output = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
       do_sample=False,
        temperature=0.3
    )

    answer = tokenizer.decode(output[0], skip_special_tokens=True)
    # remove the prompt from output
    answer = answer.replace(prompt, "").strip()

    print("Answer:", answer)

ask("What is the capital of karnataka ?", "")

def ask(question, context):
    prompt = f"Context: {context}\nQuestion: {question}\nAnswer:"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    output = model.generate(**inputs, max_new_tokens=80)
    full_output = tokenizer.decode(output[0], skip_special_tokens=True)

    # REMOVE the prompt (paragraph + question)
    answer = full_output.replace(prompt, "").strip()

    return answer

print(ask(question, context))